server:
  port: 9301
spring:
  application:
    name: admin-server
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true