server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Ascend2015/fmmall-config.git
          search-paths: files
          username: m18252711915@163.com
          password: yck4611764
  boot:
    admin:
      client:
        url: http://localhost:9301
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka